apiVersion: v1
kind: Service
metadata:
  name: model
  namespace: exp-management
spec:
  ports:
    - port: 11434
  selector:
    app: model
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: exp-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
              name: api
          volumeMounts:
            - name: model-data
              mountPath: /root/.ollama
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: model-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: exp-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
